
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModificarEquipo = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_modPresupuesto = new javax.swing.JTextField();
        tf_modEstadio = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        sp_modCopas = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        tf_modNombre = new javax.swing.JTextField();
        jb_modificarEquipo = new javax.swing.JButton();
        ModificarJugador = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        tf_ModNombreJ = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tf_modPrecioJ = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cb_modPosicionJ = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        sp_modHabilidad = new javax.swing.JSpinner();
        jLabel27 = new javax.swing.JLabel();
        sp_modTecnica = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        sp_modResistencia = new javax.swing.JSpinner();
        jb_modificarJugador = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        Mdisp = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_nombreEquipo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_presupuesto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sp_copas = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        tf_estadio = new javax.swing.JTextField();
        jb_crearJugador = new javax.swing.JButton();
        tf_nombreJugador = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_precio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        sp_habilidad = new javax.swing.JSpinner();
        sp_tecnica = new javax.swing.JSpinner();
        sp_resistencia = new javax.swing.JSpinner();
        jb_crearEquipo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cb_posicion = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        disp = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaJugadores = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaEquipos = new javax.swing.JList<>();
        jb_modificarEE = new javax.swing.JButton();
        jb_eliminarEE = new javax.swing.JButton();
        jb_modificarJJ = new javax.swing.JButton();
        jb_eliminarJJ = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaJugadoresT = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaEquiposT = new javax.swing.JList<>();
        jb_transferir = new javax.swing.JButton();

        ModificarEquipo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("EQUIPO");
        ModificarEquipo.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel18.setText("Nombre");
        ModificarEquipo.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));
        ModificarEquipo.getContentPane().add(tf_modPresupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 90, -1));
        ModificarEquipo.getContentPane().add(tf_modEstadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 90, -1));

        jLabel19.setText("Presupuesto");
        ModificarEquipo.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel20.setText("Copas");
        ModificarEquipo.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));
        ModificarEquipo.getContentPane().add(sp_modCopas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 60, -1));

        jLabel21.setText("Estadio");
        ModificarEquipo.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));
        ModificarEquipo.getContentPane().add(tf_modNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 90, -1));

        jb_modificarEquipo.setText("Modificar Equipo");
        jb_modificarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarEquipoMouseClicked(evt);
            }
        });
        ModificarEquipo.getContentPane().add(jb_modificarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jLabel22.setText("JUGADOR");

        jLabel23.setText("Nombre");

        jLabel24.setText("Precio");

        jLabel25.setText("Posicion");

        cb_modPosicionJ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Elija>", "Atacante", "Mediocampista", "Defensa", "Portero" }));

        jLabel26.setText("Habilidad");

        jLabel27.setText("Tecnica");

        jLabel28.setText("Resistencia");

        jb_modificarJugador.setText("Modificar Jugador");
        jb_modificarJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarJugadorMouseClicked(evt);
            }
        });

        jLabel30.setText("Disponible");

        javax.swing.GroupLayout ModificarJugadorLayout = new javax.swing.GroupLayout(ModificarJugador.getContentPane());
        ModificarJugador.getContentPane().setLayout(ModificarJugadorLayout);
        ModificarJugadorLayout.setHorizontalGroup(
            ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificarJugadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(171, 171, 171))
            .addGroup(ModificarJugadorLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel30)
                .addGap(69, 69, 69)
                .addComponent(Mdisp)
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ModificarJugadorLayout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addGroup(ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificarJugadorLayout.createSequentialGroup()
                                .addGroup(ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addGap(26, 26, 26)
                                .addGroup(ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_modPrecioJ)
                                    .addComponent(tf_ModNombreJ, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificarJugadorLayout.createSequentialGroup()
                                .addGroup(ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel25))
                                .addGroup(ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ModificarJugadorLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                        .addGroup(ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(sp_modResistencia, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                            .addComponent(sp_modTecnica)
                                            .addComponent(sp_modHabilidad)))
                                    .addGroup(ModificarJugadorLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(cb_modPosicionJ, 0, 1, Short.MAX_VALUE)))))
                        .addGroup(ModificarJugadorLayout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(jb_modificarJugador)))
                    .addContainerGap(114, Short.MAX_VALUE)))
        );
        ModificarJugadorLayout.setVerticalGroup(
            ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarJugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addGroup(ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mdisp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41))
            .addGroup(ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ModificarJugadorLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addGroup(ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(tf_ModNombreJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(tf_modPrecioJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(17, 17, 17)
                    .addGroup(ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(cb_modPosicionJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sp_modHabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26))
                    .addGap(18, 18, 18)
                    .addGroup(ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(sp_modTecnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(22, 22, 22)
                    .addGroup(ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel28)
                        .addComponent(sp_modResistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34)
                    .addComponent(jb_modificarJugador)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        jLabel1.setText("EQUIPO");

        jLabel2.setText("JUGADOR");

        jLabel3.setText("Nombre");

        jLabel4.setText("Presupuesto");

        jLabel5.setText("Copas");

        jLabel6.setText("Estadio");

        jb_crearJugador.setText("Crear Jugador");
        jb_crearJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearJugadorMouseClicked(evt);
            }
        });

        jLabel7.setText("Nombre");

        jLabel8.setText("Precio");

        jLabel10.setText("Habilidad");

        jLabel11.setText("Tecnica");

        jLabel12.setText("Resistencia");

        jb_crearEquipo.setText("Crear Equipo");
        jb_crearEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearEquipoMouseClicked(evt);
            }
        });

        jLabel9.setText("Posicion");

        cb_posicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Elija>", "Atacante", "Mediocampista", "Defensa", "Portero" }));

        jLabel29.setText("Disponible");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(tf_nombreEquipo)
                    .addComponent(tf_presupuesto)
                    .addComponent(sp_copas, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(tf_estadio))
                .addGap(65, 65, 65)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_precio)
                                    .addComponent(tf_nombreJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)))
                            .addComponent(jb_crearJugador, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel29)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel9)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(cb_posicion, 0, 1, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(disp)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(sp_resistencia, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                                .addComponent(sp_tecnica)
                                                .addComponent(sp_habilidad)))))))))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(jb_crearEquipo)
                    .addContainerGap(348, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cb_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sp_habilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(sp_tecnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(sp_resistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(disp)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jb_crearJugador)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(tf_nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(tf_presupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(sp_copas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(tf_estadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(289, Short.MAX_VALUE)
                    .addComponent(jb_crearEquipo)
                    .addGap(82, 82, 82)))
        );

        jTabbedPane1.addTab("Crear", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("EQUIPOS");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 24, -1, -1));

        jLabel14.setText("JUGADORES");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, 20));

        listaJugadores.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(listaJugadores);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 64, 290, 200));

        listaEquipos.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(listaEquipos);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 64, 127, 205));

        jb_modificarEE.setText("Modificar");
        jb_modificarEE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarEEMouseClicked(evt);
            }
        });
        jPanel2.add(jb_modificarEE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 275, -1, -1));

        jb_eliminarEE.setText("Eliminar");
        jb_eliminarEE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_eliminarEEMouseClicked(evt);
            }
        });
        jPanel2.add(jb_eliminarEE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 304, 75, -1));

        jb_modificarJJ.setText("Modificar");
        jb_modificarJJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarJJMouseClicked(evt);
            }
        });
        jPanel2.add(jb_modificarJJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jb_eliminarJJ.setText("Eliminar");
        jb_eliminarJJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_eliminarJJMouseClicked(evt);
            }
        });
        jPanel2.add(jb_eliminarJJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 75, -1));

        jTabbedPane1.addTab("Modificar o Eliminar", jPanel2);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Liga Española");
        arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(arbol);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Arbol", jPanel3);

        listaJugadoresT.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(listaJugadoresT);

        jLabel15.setText("EQUIPOS");

        jLabel16.setText("JUGADORES");

        listaEquiposT.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(listaEquiposT);

        jb_transferir.setText("Transferir");
        jb_transferir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_transferirMouseClicked(evt);
            }
        });
        jb_transferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_transferirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel16))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_transferir)
                .addGap(203, 203, 203))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_transferir)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transferencias", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_transferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_transferirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_transferirActionPerformed

    private void jb_crearEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearEquipoMouseClicked
        Equipo temp = new Equipo();
        temp.setNombre(tf_nombreEquipo.getText());
        temp.setPresupuesto(Double.parseDouble(tf_presupuesto.getText()));
        temp.setEstadio(tf_estadio.getText());
        temp.setCopas((Integer) sp_copas.getValue());

        DefaultListModel modelo1 = (DefaultListModel) listaEquipos.getModel();
        DefaultListModel modelo2 = (DefaultListModel) listaEquiposT.getModel();
        modelo1.addElement(temp);
        modelo2.addElement(temp);
        listaEquipos.setModel(modelo1);
        listaEquiposT.setModel(modelo2);

        DefaultTreeModel m = (DefaultTreeModel) arbol.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_equipo;
        nodo_equipo = new DefaultMutableTreeNode(temp);
        raiz.add(nodo_equipo);
        m.reload();

        JOptionPane.showMessageDialog(this, "Creado");
    }//GEN-LAST:event_jb_crearEquipoMouseClicked

    private void jb_crearJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearJugadorMouseClicked
        Jugador temp = new Jugador();
        temp.setNombre(tf_nombreJugador.getText());
        temp.setPrecio(Double.parseDouble(tf_precio.getText()));
        temp.setPosicion((String) cb_posicion.getSelectedItem());
        temp.setHabilidad((Integer) sp_habilidad.getValue());
        temp.setTecnica((Integer) sp_tecnica.getValue());
        temp.setResistencia((Integer) sp_resistencia.getValue());
        temp.setDisponibilidad(disp.isSelected());

        DefaultListModel modelo1 = (DefaultListModel) listaJugadores.getModel();
        DefaultListModel modelo2 = (DefaultListModel) listaJugadoresT.getModel();
        modelo1.addElement(temp);
        modelo2.addElement(temp);
        listaJugadores.setModel(modelo1);
        listaJugadoresT.setModel(modelo2);

        JOptionPane.showMessageDialog(this, "Creado");
    }//GEN-LAST:event_jb_crearJugadorMouseClicked

    private void jb_modificarEEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarEEMouseClicked

        DefaultListModel modeloLISTA1 = (DefaultListModel) listaEquipos.getModel();
        equipoSeleccionado = (Equipo) modeloLISTA1.get(listaEquipos.getSelectedIndex());
        ModificarEquipo.setVisible(true);
        ModificarEquipo.pack();//Acoplar el ta,ano de las subventanas a los controles de hi dentro
        //ModificarEquipo.setModal(true);

    }//GEN-LAST:event_jb_modificarEEMouseClicked

    private void jb_modificarJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarJugadorMouseClicked

        jugadorSeleccionado.setNombre(tf_ModNombreJ.getText());
        jugadorSeleccionado.setPrecio(Double.parseDouble(tf_modPrecioJ.getText()));
        jugadorSeleccionado.setPosicion((String) cb_modPosicionJ.getSelectedItem());
        jugadorSeleccionado.setHabilidad((Integer) sp_modHabilidad.getValue());
        jugadorSeleccionado.setTecnica((Integer) sp_modTecnica.getValue());
        jugadorSeleccionado.setResistencia((Integer) sp_modResistencia.getValue());
        jugadorSeleccionado.setDisponibilidad(Mdisp.isSelected());
        JOptionPane.showMessageDialog(this, "Modificado");
        ModificarJugador.setVisible(false);

    }//GEN-LAST:event_jb_modificarJugadorMouseClicked

    private void jb_modificarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarEquipoMouseClicked

        equipoSeleccionado.setNombre(tf_modNombre.getText());
        equipoSeleccionado.setPresupuesto(Double.parseDouble(tf_modPresupuesto.getText()));
        equipoSeleccionado.setEstadio(tf_modEstadio.getText());
        equipoSeleccionado.setCopas((Integer) sp_modCopas.getValue());
        JOptionPane.showMessageDialog(this, "Modificado");
        ModificarEquipo.setVisible(false);
    }//GEN-LAST:event_jb_modificarEquipoMouseClicked

    private void jb_modificarJJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarJJMouseClicked

        DefaultListModel modeloLISTA1 = (DefaultListModel) listaJugadores.getModel();
        jugadorSeleccionado = (Jugador) modeloLISTA1.get(listaJugadores.getSelectedIndex());
        ModificarJugador.setVisible(true);
        ModificarJugador.pack();//Acoplar el ta,ano de las subventanas a los controles de hi dentro
        //ModificarJugador.setModal(true);
    }//GEN-LAST:event_jb_modificarJJMouseClicked

    private void jb_eliminarEEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_eliminarEEMouseClicked
        DefaultListModel m = (DefaultListModel) listaEquipos.getModel();
        m.remove(listaEquipos.getSelectedIndex());
        listaEquipos.setModel(m);
        listaEquiposT.setModel(m);
    }//GEN-LAST:event_jb_eliminarEEMouseClicked

    private void jb_eliminarJJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_eliminarJJMouseClicked
        DefaultListModel m = (DefaultListModel) listaJugadores.getModel();
        m.remove(listaJugadores.getSelectedIndex());
        listaJugadores.setModel(m);
        listaJugadores.setModel(m);
    }//GEN-LAST:event_jb_eliminarJJMouseClicked

    private void jb_transferirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_transferirMouseClicked
        DefaultListModel m = (DefaultListModel) listaEquiposT.getModel();
        equipoSeleccionado = (Equipo) m.get(listaEquiposT.getSelectedIndex());
        DefaultListModel m2 = (DefaultListModel) listaJugadoresT.getModel();
        jugadorSeleccionado = (Jugador) m2.get(listaJugadoresT.getSelectedIndex());
        if(jugadorSeleccionado.getPrecio()<equipoSeleccionado.getPresupuesto() && jugadorSeleccionado.getDisponibilidad()==true){
            equipoSeleccionado.listaJugadores.add(jugadorSeleccionado);
            jugadorSeleccionado.setDisponibilidad(false);
            equipoSeleccionado.setPresupuesto(equipoSeleccionado.getPresupuesto()-jugadorSeleccionado.getPrecio());
            DefaultTreeModel modeloARBOL = (DefaultTreeModel) arbol.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if(((Equipo)raiz.getChildAt(i)).getNombre().equals(equipoSeleccionado.getNombre())){
                    DefaultMutableTreeNode p =  new DefaultMutableTreeNode(jugadorSeleccionado);
                    ((DefaultMutableTreeNode)raiz.getChildAt(i)).add(p);
                    System.out.println("dsfjkhaldsk");
                }
            }
        }else{
            JOptionPane.showMessageDialog(this,"No se puede comprar a "+jugadorSeleccionado.getNombre());
        }
    }//GEN-LAST:event_jb_transferirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Mdisp;
    private javax.swing.JDialog ModificarEquipo;
    private javax.swing.JDialog ModificarJugador;
    private javax.swing.JTree arbol;
    private javax.swing.JComboBox<String> cb_modPosicionJ;
    private javax.swing.JComboBox<String> cb_posicion;
    private javax.swing.JCheckBox disp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_crearEquipo;
    private javax.swing.JButton jb_crearJugador;
    private javax.swing.JButton jb_eliminarEE;
    private javax.swing.JButton jb_eliminarJJ;
    private javax.swing.JButton jb_modificarEE;
    private javax.swing.JButton jb_modificarEquipo;
    private javax.swing.JButton jb_modificarJJ;
    private javax.swing.JButton jb_modificarJugador;
    private javax.swing.JButton jb_transferir;
    private javax.swing.JList<String> listaEquipos;
    private javax.swing.JList<String> listaEquiposT;
    private javax.swing.JList<String> listaJugadores;
    private javax.swing.JList<String> listaJugadoresT;
    private javax.swing.JSpinner sp_copas;
    private javax.swing.JSpinner sp_habilidad;
    private javax.swing.JSpinner sp_modCopas;
    private javax.swing.JSpinner sp_modHabilidad;
    private javax.swing.JSpinner sp_modResistencia;
    private javax.swing.JSpinner sp_modTecnica;
    private javax.swing.JSpinner sp_resistencia;
    private javax.swing.JSpinner sp_tecnica;
    private javax.swing.JTextField tf_ModNombreJ;
    private javax.swing.JTextField tf_estadio;
    private javax.swing.JTextField tf_modEstadio;
    private javax.swing.JTextField tf_modNombre;
    private javax.swing.JTextField tf_modPrecioJ;
    private javax.swing.JTextField tf_modPresupuesto;
    private javax.swing.JTextField tf_nombreEquipo;
    private javax.swing.JTextField tf_nombreJugador;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_presupuesto;
    // End of variables declaration//GEN-END:variables
    Equipo equipoSeleccionado;
    Jugador jugadorSeleccionado;

}
